<?xml version="1.0" encoding="ISO-8859-1"?>
<definitions xmlns:tns="http://www.ans.gov.br/tiss/ws/tipos/tisssolicitacaodemonstrativoretorno/v30202" xmlns:ans="http://www.ans.gov.br/padroes/tiss/schemas" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="tissSolicitacaoDemonstrativoRetorno" targetNamespace="http://www.ans.gov.br/tiss/ws/tipos/tisssolicitacaodemonstrativoretorno/v30202">
	<types>
		<schema xmlns:soap11-enc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns="http://www.w3.org/2001/XMLSchema">
			<import namespace="http://www.ans.gov.br/padroes/tiss/schemas" schemaLocation="tissWebServicesV3_02_02.xsd"/>
		</schema>
	</types>
	<message name="tissSolicitacaoDemonstrativoRetorno_Request">
		<part name="solicitacaoDemonstrativoRetorno" element="ans:solicitacaoDemonstrativoRetornoWS"/>
	</message>
	<message name="tissSolicitacaoDemonstrativoRetorno_Response">
		<part name="demonstrativoRetorno" element="ans:demonstrativoRetornoWS"/>
	</message>
	<message name="tissFault">
		<part name="tissFault" element="ans:tissFaultWS"/>
	</message>
	<portType name="tissSolicitacaoDemonstrativoRetorno_PortType">
		<operation name="tissSolicitacaoDemonstrativoRetorno_Operation">
			<input message="tns:tissSolicitacaoDemonstrativoRetorno_Request"/>
			<output message="tns:tissSolicitacaoDemonstrativoRetorno_Response"/>
			<fault name="TissFault" message="tns:tissFault"/>
		</operation>
	</portType>
	<binding name="tissSolicitacaoDemonstrativoRetorno_Binding" type="tns:tissSolicitacaoDemonstrativoRetorno_PortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<operation name="tissSolicitacaoDemonstrativoRetorno_Operation">
			<soap:operation soapAction=""/>
			<input>
				<soap:body use="literal"/>
			</input>
			<output>
				<soap:body use="literal"/>
			</output>
			<fault name="TissFault">
				<soap:fault name="TissFault" use="literal"/>
			</fault>
		</operation>
	</binding>
	<service name="tissSolicitacaoDemonstrativoRetorno">
		<port name="tissSolicitacaoDemonstrativoRetorno_Port" binding="tns:tissSolicitacaoDemonstrativoRetorno_Binding">
			<soap:address/>
		</port>
	</service>
</definitions>
